AWSTemplateFormatVersion: 2010-09-09
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-aws-serverless.html
Transform: AWS::Serverless-2016-10-31
Description: Room Reservation Services
Parameters:
  NameSpace:
    Type: String
    Description: Prefix for all services that are created by this stack
    Default: rrapp-
Globals:
  Api:
    Cors:
      AllowOrigin: '''*'''
      AllowHeaders: '''Content-Type'''
      AllowMethods: '''GET,OPTIONS'''
Resources:
  # DynamoDB tables
  #  - TODO: initialize data (see Serverlesspresso: FillDatabasesCustomResource)
  RoomTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${NameSpace}rooms
      AttributeDefinitions:
        - AttributeName: roomNr
          AttributeType: S
#        - AttributeName: description
#          AttributeType: S
      KeySchema:
        - AttributeName: roomNr
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
    Metadata:
      SamResourceId: RoomTable
  RoomReservationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${NameSpace}room-reservations
      AttributeDefinitions:
        - AttributeName: uuid
          AttributeType: S
#        - AttributeName: date
#          AttributeType: S
#        - AttributeName: room
#          AttributeType: S
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
    Metadata:
      SamResourceId: RoomReservationsTable
      # TODO create GSI
  # Lambda Functions
  CreateRoomReservation:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://room-reservation/app/lambdas.jar
      Handler: de.ars.rooms.reservations.lambda.CreateRoomReservationHandler::handleRequest
      Runtime: 'Java 17'
      Timeout: 15
      MemorySize: 512
      Environment:
        Variables:
          ROOM_RESERVATIONS_TABLE:
            Ref: RoomReservationsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Ref: RoomReservationsTable
    Metadata:
      SamResourceId: CreateRoomReservation
