name: Application Code (CI)

on:
  push:
    branches: [ "main" ]
    paths: ["app/**"]
  pull_request:
    branches: [ "main" ]
    paths: ["app/**"]
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        gradle-version: 8.2.1
        arguments: -b 'app/build.gradle' build
    - uses: actions/upload-artifact@v3
      with:
        name: built-artifacts
        path: |
          app/**/build/libs/*.jar
          app/**/build/distributions/*.zip
        if-no-files-found: error

  S3-deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: built-artifacts
    - name: Collect files for S3 upload
      run: mkdir '.publish-s3' && find '.' -type f \( -name '*.jar' -o -name '*.zip' \) -exec cp -t '.publish-s3' {} +
    - name: Upload files to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete
      env:
        AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
        DEST_DIR: ${{ vars.AWS_S3_BUCKET_DIRECTORY_APP }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-central-1'  # optional: defaults to us-east-1
        SOURCE_DIR: '.publish-s3'   # optional: defaults to entire repository
