name: Stack (CI)

on:
  push:
    branches: [ "main" ]
    paths: ["stack/**"]
  workflow_dispatch:
    inputs:
      s3Bucket:
        description: 'Name of the S3 Bucket to upload'
        required: true
        default: ${{ env.AWS_S3_BUCKET }}
      s3BucketDirectory:
        description: 'Sub Directory of the S3 Bucket to upload (use / to deploy to the root)'
        required: true
        default: ${{ env.AWS_S3_BUCKET_DIRECTORY_STACK }}

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  S3-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - name: Upload files to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete
      env:
        AWS_S3_BUCKET: ${{ github.event.inputs.s3Bucket }}
        DEST_DIR: ${{ github.event.inputs.s3BucketDirectory }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-central-1'  # optional: defaults to us-east-1
        SOURCE_DIR: 'stack'         # optional: defaults to entire repository
